# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-19 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirizzo', models.CharField(max_length=100)),
                ('citta', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=2)),
                ('regione', models.CharField(max_length=50)),
                ('latitudine', models.FloatField(blank=True, default=0, null=True)),
                ('longitudine', models.FloatField(blank=True, default=0, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('pet_coins', models.IntegerField(default=0)),
                ('foto_profilo', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('pet_sitter', models.BooleanField(default=False)),
                ('nome_pet', models.CharField(default='', max_length=50, null=True)),
                ('pet', models.CharField(default='', max_length=50, null=True)),
                ('razza', models.CharField(default='', max_length=50, null=True)),
                ('eta', models.PositiveIntegerField(null=True)),
                ('caratteristiche', models.CharField(default='', max_length=250, null=True)),
                ('foto_pet', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('descrizione', models.CharField(default='', max_length=250, null=True)),
                ('hobby', models.CharField(default='', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
