# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-19 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0002_auto_20200119_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitudine',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitudine',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
